package com.github.leetcode.easy;

/**
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 * @author liuzhongda
 *
 */
public class Leetcode389 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}
	
	public char findTheDifference(String s, String t) {
		char cValue=0x00;
		for(char c:s.toCharArray()) {
			cValue^=c;
		}
		for(char c:t.toCharArray()) {
			cValue^=c;
		}
		return cValue;
	}

}
